{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-metrics-exporter.fullname" . }}-secret
  labels:
    {{- include "azure-metrics-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Credenciales del Service Principal de Azure
  # Estos valores vienen de values.yaml (o se sobrescriben por entorno)
  tenantId: {{ .Values.azure.tenantId | quote }}
  clientId: {{ .Values.azure.clientId | quote }}
  clientSecret: {{ .Values.azure.clientSecret | quote }}
  subscriptionId: {{ .Values.azure.subscriptionId | quote }}
{{- end }}
